# Generated by Django 5.1.1 on 2024-10-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmaster',
            old_name='rentholder_id',
            new_name='rentholder',
        ),
    ]
