# Generated by Django 5.1.1 on 2024-10-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_rentholder_id_bookingmaster_rentholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='login_id',
            new_name='login',
        ),
    ]
