# Generated by Django 5.1.1 on 2024-10-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentholder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='login_id',
            new_name='login',
        ),
    ]
