# Generated by Django 5.1.1 on 2024-10-11 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_brand'),
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('contact_no', models.BigIntegerField()),
                ('address', models.TextField()),
                ('proof', models.ImageField(upload_to='images/')),
                ('pincode', models.BigIntegerField()),
                ('imagefile', models.ImageField(upload_to='images/')),
                ('register_date', models.DateField()),
                ('district_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='adminapp.district')),
                ('login_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login', to='guest.login')),
                ('state_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='adminapp.state')),
            ],
        ),
    ]
