# Generated by Django 5.1.1 on 2024-10-11 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_brand'),
        ('guest', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='rentholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentholder_name', models.CharField(max_length=50)),
                ('rentholder_email', models.CharField(max_length=50)),
                ('rentholder_contact', models.BigIntegerField()),
                ('rentholder_address', models.TextField()),
                ('rentholder_proof', models.ImageField(upload_to='images/')),
                ('rentholder_pincode', models.BigIntegerField()),
                ('rentholder_imagefile', models.ImageField(upload_to='images/')),
                ('rentholder_registerdate', models.DateField()),
                ('rentholder_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.district')),
                ('rentholder_login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.login')),
                ('rentholder_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.state')),
            ],
        ),
    ]
