# Generated by Django 5.1.1 on 2024-10-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_rentholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='login_id',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='state_id',
            new_name='state',
        ),
    ]
